apiVersion: v1
kind: ConfigMap
metadata:
  name: kueue-manager-config
  namespace: kueue-system
data:
  controller_manager_config.yaml: |
    apiVersion: config.kueue.x-k8s.io/v1beta2
    kind: Configuration
    health:
      healthProbeBindAddress: :8081
    metrics:
      bindAddress: :8443
    webhook:
      port: 9443
    leaderElection:
      leaderElect: true
      resourceName: c1f6bfd2.kueue.x-k8s.io
    clientConnection:
      qps: 300
      burst: 500
    fairSharing:
      preemptionStrategies: [LessThanOrEqualToFinalShare, LessThanInitialShare]
    admissionFairSharing:
      usageHalfLifeTime: "1m"
      usageSamplingInterval: "1s"
      resourceWeights:
        example.com/simulated-gpu: 1
    integrations:
      frameworks:
        - "batch/job"
        - "pod"
        - "deployment"
        - "statefulset"
